### PR TITLE
[Bug fix] Here's the fix for your code :)

### PR DESCRIPTION
**Pull request by SonicandTailsCD**
Hello @spyingcreeper09 :)
I switched the code base to Mineflayer (you'll have to run `npm ci` after recloning.
I moved most of the code to `onSpawn()` and bug fixed.
The reason it wasn't working was because `minecraft-protocol` for some reason calls for asynchronous and Mineflayer is more like a background task. :)

Take your time to review the code and use `test_mcprotocol.js` as a simple way to test `minecraft-protocol` (Remember! Change the constant `minecraft`'s `require(…)` to the module you want to test THEN, if it’s `minecraft-protocol` you want to test, change `minecraft.createBot(options)` to `minecraft.createClient(options`.). :)

### CODE REVIEW

**Comment by SonicandTailsCD** [comment]
Oh shoot.
I just realized you already attempted to fix it... I'm sorry :(

**Comment by SonicandTailsCD** [comment]
Since you've already applied corrections, and I've applied corrections...
I'm pretty sure you wish to keep your corrections on top of mine...

**Comment by SonicandTailsCD** [comment]
I merged your latest changes with mine (still does not work with `minecraft-protocol`). If you wish to apply the change, go ahead! - and if you don't want to merge, that's okay - my repo will remain active so you can copy and paste the code from my repo to yours.
Always happy to help is all. :)

**Review by spyingcreeper09 — APPROVED** [review]
You sound like you know what your doing. You are also putting a bit more effort into this then I am. Good work!

**Comment by SonicandTailsCD** [comment]
Aww thanks! I'm always happy to help, especially when it comes to programming :) 
If there's anything else I can code for you, just send me a message through my repos or something. Happy coding! :D

**Comment by SonicandTailsCD** [comment]
## ⚠️ Reminder: My changes were not merged
Now now, I'm not begging you to merge my changes. This is a reminder that you've approved my changes, yet not accepted them to be merged into your repository.
I'm currently working on adding pathfinding and simply teleporting to owner on command, and that would be my final change. It's still incomplete, and I do NOT want to commit a broken change, but if you simply don't want me to import this change, go ahead and merge or close the pull request. :) 
Sorry if I'm annoying, I'm just trying to be helpful ^-^

In case you don't know...
- "Merging" means that, all the changes that I've done will be applied to your repository. This is good if you wish to keep the changes in one place! Double-check the files' code to make sure that's what you want :) 
- If you wish to keep our changes separate, DO NOT merge. We can keep this PR open and talk, or you can close it if you wish. :) 

Need further explanation? I'll help you, just ask any questions and I'll answer them as good as possible! :) 

(I just noticed you credited me! Thank you so much! I'm so glad I helped :) )

**Comment by SonicandTailsCD** [comment]
I'm unfortunately taking very long in adding pathfinding and teleports to owner. This is actually hard to do - I hope soon I'll be done :) 
It's 20:06 GMT-08:00 right now, so I will sign off for today. Goodbye for now! :)

**Comment by spyingcreeper09** [comment]
> ## ⚠️ Reminder: My changes were not merged
> Now now, I'm not begging you to merge my changes. This is a reminder that you've approved my changes, yet not accepted them to be merged into your repository. I'm currently working on adding pathfinding and simply teleporting to owner on command, and that would be my final change. It's still incomplete, and I do NOT want to commit a broken change, but if you simply don't want me to import this change, go ahead and merge or close the pull request. :) Sorry if I'm annoying, I'm just trying to be helpful ^-^
> 
> In case you don't know...
> 
> * "Merging" means that, all the changes that I've done will be applied to your repository. This is good if you wish to keep the changes in one place! Double-check the files' code to make sure that's what you want :)
> * If you wish to keep our changes separate, DO NOT merge. We can keep this PR open and talk, or you can close it if you wish. :)
> 
> Need further explanation? I'll help you, just ask any questions and I'll answer them as good as possible! :)
> 
> (I just noticed you credited me! Thank you so much! I'm so glad I helped :) )

Sorry, i am new to github and dont use it almost at all. Can you tell me how to merge them please?

**Comment by SonicandTailsCD** [comment]
> Sorry, i am new to github and dont use it almost at all. Can you tell me how to merge them please?

I'm so sorry, I didn't know...
Sure, I'll help, but **please** check all changes made through [here](https://github.com/spyingcreeper09/Minecraft-Protocol-Basic-Chat-Bot/pull/2/files) before you merge. This may have changes you do NOT want, and I will do my best to resolve those. :)
Here's the steps **with images**:
1. Make sure you're looking at the comment section's end (where you type your comment). 
2. Click "Merge pull request": 
Screenshot from 2024-05-09 20-08-02
3. Edit the text to anything you'd like, **recheck** those are the changes you want to apply to **your** repository, then click "Confirm merge":
Screenshot from 2024-05-09 20-09-32
4. (May not show up) In case you're asked that a certain branch can be safely deleted, like the below one, do it:
Screenshot from 2024-05-09 20-09-55

**You're done~**
Changes are merged to your repository and your repo will have my code imported.

**WARNING**: Changes made by me will be applied to your repository if you merge, and if you wish to keep my changes completely separate from your repository, DO NOT merge (unless you wish to keep my commits memorialized in your account as a contributor). :) 

Let me know if you have any other questions! Always happy to clarify problems :)

**Comment by SonicandTailsCD** [comment]
Hi @spyingcreeper09 :) 
At this point, 7 days have passed.
I'm assuming you do **not** want to merge my changes.

If 14 days (yes, including the current 7 days) pass, I will close this pull request for you to have uncluttered view of your repo's pulls. :) 

Let me know if you have any other questions. :D 
Sorry if I'm annoying, I'm just trying to help :) 

(Haven't updated, because I do not want you to merge a broken PR. The current code in my PC is broken so I'm taking a bit of time to actually start commuting changes.)

**Comment by spyingcreeper09** [comment]
Hi, sorry about that. I do want to merge them, honestly. It’s just that i dint have the time right now. It’s ether working or school or chores or whatever comes up. I will try to get that done tomorrow if I can. Again im sorry about the inconvenience.

**Comment by SonicandTailsCD** [comment]
> Hi, sorry about that. I do want to merge them, honestly. It’s just that i dint have the time right now. It’s ether working or school or chores or whatever comes up. I will try to get that done tomorrow if I can. Again im sorry about the inconvenience. 

Oh... I'm so sorry, @spyingcreeper09... I didn't know :( 
It's alright, I understand completely. I'm sorry if I came across as manipulative or as a begger... :( 

Please simply take your time. My intention wasn't making you feel bad, I'm so sorry... :( 

When reviewing the changes listed please do double-check those are the changes you wish to merge. Again, sorry I came across as bad... Take care for now, good night :(

**Comment by spyingcreeper09** [comment]
ok, i think i have completed it. Please tell me if i did anything worng or need to change anything else

**Comment by SonicandTailsCD** [comment]
### WHOOPS!
You've merged changes to my repository, not yours!
It's alright though, your error can be undone. Allow me a moment to undo the change. 

What did you click, may I ask? :)

**Comment by SonicandTailsCD** [comment]
Upon further inspection, are these changes you wish to apply? It seems like you wish to revert a few changes and possibly make the code unusable. :(

**Comment by SonicandTailsCD** [comment]
I will test this new code in a bit. Please allow me a moment.

**Comment by spyingcreeper09** [comment]
Oh, im so sorry. My bad. Hopefully its not too hard of a fix. I clicked the merge repository and then I had to solve some conflicts but if it edited your repository then im guessing thats where it went wrong

**Comment by SonicandTailsCD** [comment]
It's okay! Don't worry, I think I undid all accidental merges. :) 

While I don't suggest to directly give me collaborator permission, try taking a screenshot. What do you see here? If you can provide that screenshot, I can help you no problem! :)

**Comment by SonicandTailsCD** [comment]
Hi @spyingcreeper09 :) 
It's been a while, and I haven't heard back from you.
Since I haven't heard back from you, and since you've told me you're mostly busy, this is mostly a reminder that changes were not merged.

Again, just let me know how I can help you. 
Please also send me a screenshot of what you see soon! This will help me help you merge changes :)

**Comment by spyingcreeper09** [comment]
Hi, sorry about that. Your going to need to give me a few more days. Sorry about this whole situation. I just wanted to reply to show you i haven’t ghosted you or something. Here is what i am seeing. Im not going to touch it because last time i did i apparently merged mine to yours
IMG_2942
IMG_2941

**Comment by SonicandTailsCD** [comment]
I'm so sorry, I'm not supposed to be pressuring you! :(
It's okay, I completely understand. Take all the time you need, okay?

If you're up for it, I can directly upload the changes to your repo and maintain it for you. The TypeScript upgrade will not be uploaded to your repository as it's unnecessary. 
I'm trying to make it accessible to users so they can have fun with the bot, while your repo's meant as a very basic one that encourages users to build upon. It's just best to see if users want instant enjoyment/fun, or a base to build their own fun bot. How's that sound? 
If you want the TypeScript functionality, please let me know! :)

To do this merge without problems, I'll need *collaborator access*. Here's how:
1. First, go to your repository's *collaborator settings*. Click [here](https://github.com/spyingcreeper09/Minecraft-Protocol-Basic-Chat-Bot/settings/access) for your repo's settings :)
2. Tap on "Add people" (DO NOT do this if you're not willing to give me access)
3. Type my name, or anyone else's name at your will, then tap the name
4. Tap "Add [person] to this repository"
5. Now wait until I accept the invite. I'll then be able to upload changes directly, and maintain the repository while you're gone. :)

To show my respect to you for your patience and care, even when I was a tad bit too pushy, I've given you *collaborator* access to my [Roboticraft remake](https://github.com/SonicandTailsCD/Roboticraft)! Please check it out. :)

Thanks for bearing with me, @spyingcreeper09 :)

**Comment by spyingcreeper09** [comment]
Ok, i think i will do that. Thanks for offering to manage it. You don't need to keep it too maintained as not many people will use it. Also, i did check out the robocraft and it looks very cool. I will play around with it sometime. Also, i need to apologize, not you. I haven’t had a chance to get to you and you just had one question the entire time. I could have probably found tome to work this out. Sorry about that. I feel that you deserve more credit on this then i do lol. I do thank you for being with me this entire time. I am willing to provide some functionality from my commands because of your patience. Just ask for one and i can provide it. Again, thank you.

**Comment by SonicandTailsCD** [comment]
> Ok, i think i will do that. Thanks for offering to manage it. You don't need to keep it too maintained as not many people will use it. Also, i did check out the robocraft and it looks very cool. I will play around with it sometime. Also, i need to apologize, not you. I haven’t had a chance to get to you and you just had one question the entire time. I could have probably found tome to work this out. Sorry about that. I feel that you deserve more credit on this then i do lol. I do thank you for being with me this entire time. I am willing to provide some functionality from my commands because of your patience. Just ask for one and i can provide it. Again, thank you.

Aww, thank you so much! I'm just a humble hedgehog trying to help people, and I'm so happy that you actually like me, even when I'm a bit chatty and pushy 😅

I'm glad you checked out [Roboticraft](https://github.com/SonicandTailsCD/Roboticraft)! Please check your email. I've gave you *collaborator access*, you just need to tap the link (Do NOT click on any link other than from noreply@github.com) if you want it.

Thank you so much for actually giving me collaborator access. As it's pretty late (22:28 GMT-07:00), I'll sleep for now. I hope I can help maintain your repository ASAP :D 

If you have any issues or concerns with my collaboration actions, please send me a message to sonicandtailscd@outlook.com. I'll immediately notice and will take proper action. :) 

I accept your apology, it's all forgiven. Simply don't dwell within the thought too much, it will hurt you more. I completely understand - you need your time. :) 
Speaking of which, I have an exam coming up 07/06/2024 07:00 PST, and I won't be able to answer often for around this time to that time. Thanks for your understanding, I hope you don't mind :) 

Hahaha! I 100% agree, once I was working with a (now-deleted) user (@678435021) and we were programming for fun and all, but I realized that I was sooo far behind! I credited him of course lol 😂 
It all makes sense, don't worry @spyingcreeper09 :) 

I thank you for staying and continuing to chat, even after all this time. I'm so thrilled to be a part of your repo's collaborators. I'll hopefully upload the fixes tomorrow or at 08/06/2024 PST. 

This is Sonic saying, peace out and have a good day! ✌🏻

**Comment by SonicandTailsCD** [comment]
Hi @spyingcreeper09 :) 
I'm done! I've uploaded the big fix. 
Thanks for letting me have Collaborator access. I'm at your service - any code you wish to add, consider it done! :) 

Should I leave this PR open? :)

**Comment by spyingcreeper09** [comment]
Thanks, and you can leave it open if you want

**Comment by SonicandTailsCD** [comment]
Alright then! 
Please send a comment here if you want any new feature, share code ideas or just want to chat. My code skills are at your service! 🫡

I'll keep the PR open as you requested. Thank you for trusting me, I won't let you down! :)

**Pull request closed without merging**
